import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, '..');
const researchDir = path.join(repoRoot, 'data', 'research');
const inputPath = path.join(researchDir, 'campus_locations.2026-04-21.csv');
const outputPath = path.join(repoRoot, 'src', 'data', 'campusResearch.ts');

function parseCsv(text) {
  const rows = [];
  let row = [];
  let cell = '';
  let quoted = false;

  for (let index = 0; index < text.length; index += 1) {
    const char = text[index];
    const next = text[index + 1];

    if (quoted) {
      if (char === '"') {
        if (next === '"') {
          cell += '"';
          index += 1;
        } else {
          quoted = false;
        }
      } else {
        cell += char;
      }
      continue;
    }

    if (char === '"') {
      quoted = true;
      continue;
    }

    if (char === ',') {
      row.push(cell);
      cell = '';
      continue;
    }

    if (char === '\n') {
      row.push(cell);
      rows.push(row);
      row = [];
      cell = '';
      continue;
    }

    if (char === '\r') continue;

    cell += char;
  }

  if (cell.length > 0 || row.length > 0) {
    row.push(cell);
    rows.push(row);
  }

  return rows;
}

async function readCsvObjects(filePath) {
  const text = await fs.readFile(filePath, 'utf8');
  const rows = parseCsv(text).filter((row) => row.some((cell) => cell !== ''));
  const [header, ...body] = rows;
  return body.map((row) => {
    const record = {};
    header.forEach((column, index) => {
      record[column] = row[index] ?? '';
    });
    return record;
  });
}

function formatJson(value) {
  return JSON.stringify(value, null, 2);
}

async function main() {
  let rawRows = [];
  try {
    rawRows = await readCsvObjects(inputPath);
  } catch {
    rawRows = [];
  }

  const byMoeCode = {};
  const counts = {
    campusRows: 0,
    campusSchools: 0,
    withCoordinates: 0,
    highConfidenceRows: 0,
    mediumConfidenceRows: 0,
    lowConfidenceRows: 0,
  };

  for (const row of rawRows) {
    if (!row.moeCode?.trim()) continue;

    const record = {
      campusName: row.campusName?.trim() || '主校区',
      campusAddress: row.campusAddress?.trim() || '',
      province: row.province?.trim() || '',
      city: row.city?.trim() || '',
      district: row.district?.trim() || '',
      lat: row.lat?.trim() ? Number(row.lat) : undefined,
      lng: row.lng?.trim() ? Number(row.lng) : undefined,
      undergraduateScope: row.undergraduateScope?.trim() || 'unknown',
      freshmanOnly: row.freshmanOnly?.trim() || 'unknown',
      mainCampusType: row.mainCampusType?.trim() || undefined,
      nearestMetroStation: row.nearestMetroStation?.trim() || '',
      metroDistanceKm: row.metroDistanceKm?.trim() ? Number(row.metroDistanceKm) : undefined,
      sourceTitle: row.sourceTitle?.trim() || '',
      sourceUrl: row.sourceUrl?.trim() || '',
      sourceDate: row.sourceDate?.trim() || '',
      confidence: row.confidence?.trim() || 'low',
      notes: row.notes?.trim() || '',
    };

    if (!byMoeCode[row.moeCode]) byMoeCode[row.moeCode] = [];
    byMoeCode[row.moeCode].push(record);

    counts.campusRows += 1;
    if (Number.isFinite(record.lat) && Number.isFinite(record.lng)) counts.withCoordinates += 1;
    if (record.confidence === 'high') counts.highConfidenceRows += 1;
    if (record.confidence === 'medium') counts.mediumConfidenceRows += 1;
    if (record.confidence === 'low') counts.lowConfidenceRows += 1;
  }

  for (const moeCode of Object.keys(byMoeCode)) {
    byMoeCode[moeCode] = byMoeCode[moeCode]
      .sort((left, right) => left.campusName.localeCompare(right.campusName, 'zh-Hans-CN'));
  }

  counts.campusSchools = Object.keys(byMoeCode).length;

  const output = `// Generated by scripts/build_campus_research.mjs. Do not edit by hand.\n`
    + `export interface CampusResearchRecord {\n`
    + `  campusName: string;\n`
    + `  campusAddress?: string;\n`
    + `  province?: string;\n`
    + `  city?: string;\n`
    + `  district?: string;\n`
    + `  lat?: number;\n`
    + `  lng?: number;\n`
    + `  undergraduateScope?: string;\n`
    + `  freshmanOnly?: string;\n`
    + `  mainCampusType?: string;\n`
    + `  nearestMetroStation?: string;\n`
    + `  metroDistanceKm?: number;\n`
    + `  sourceTitle?: string;\n`
    + `  sourceUrl?: string;\n`
    + `  sourceDate?: string;\n`
    + `  confidence?: 'high' | 'medium' | 'low';\n`
    + `  notes?: string;\n`
    + `}\n\n`
    + `export const campusResearchByMoeCode: Record<string, CampusResearchRecord[]> = ${formatJson(byMoeCode)};\n\n`
    + `export const campusResearchMeta = ${formatJson({
      generatedAt: new Date().toISOString(),
      input: 'data/research/campus_locations.2026-04-21.csv',
      counts,
    })};\n`;

  await fs.writeFile(outputPath, output, 'utf8');
  console.log(`wrote ${path.relative(repoRoot, outputPath)}`);
  console.log(JSON.stringify(counts, null, 2));
}

await main();
