// Generated by scripts/build_admission_channels.mjs. Do not edit by hand.
// Source: data/research/admission_channels.2026-09-08.csv
//
// 只收有官方招生章程佐證的結論。沒有記錄的學校在 A6 一律落回 regular 先驗，
// 寧可少排除，不可誤殺。

import type { SchoolAdmissionChannels } from './runtimeTypes'

export const admissionChannelsByMoeCode: Record<string, SchoolAdmissionChannels> = {
  "4111014430": {
    "schoolName": "中国科学院大学",
    "year": 2026,
    "regularProvinces": [
      "北京",
      "江苏",
      "浙江",
      "山东",
      "陕西",
      "湖南",
      "四川"
    ],
    "comprehensiveProvinces": [
      "北京",
      "江苏",
      "浙江",
      "山东",
      "陕西",
      "湖南",
      "四川"
    ],
    "source": {
      "title": "中国科学院大学2026年本科招生章程",
      "url": "https://admission.ucas.ac.cn/ShowArticle/Article/4719aea6-edb5-4446-9f2d-cbcc771da521/3ecb7777-078d-42bd-b474-408693b74a94",
      "date": "2026-05-29",
      "confidence": "high"
    },
    "notes": "这7个省市是综合评价（提前批）与普通高考（一批次）并行；普通批以100%比例调阅档案，因此不属于综评专属"
  },
  "4131014423": {
    "schoolName": "上海科技大学",
    "year": 2025,
    "regularProvinces": [
      "安徽"
    ],
    "comprehensiveProvinces": [
      "北京",
      "天津",
      "辽宁",
      "上海",
      "江苏",
      "浙江",
      "福建",
      "江西",
      "山东",
      "河南",
      "湖北",
      "湖南",
      "重庆",
      "四川",
      "贵州",
      "云南",
      "陕西",
      "甘肃"
    ],
    "source": {
      "title": "上海科技大学2025年本科招生章程",
      "url": "https://www.shanghaitech.edu.cn/2025/0519/c1001a1111080/page.htm",
      "date": "2025-05-19",
      "confidence": "high"
    },
    "notes": "18省以校园开放日为核心的综合评价招生；仅安徽在普通本科批按投档成绩排序录取"
  },
  "4131016404": {
    "schoolName": "上海纽约大学",
    "year": 2026,
    "regularProvinces": [],
    "comprehensiveProvinces": [
      "all"
    ],
    "source": {
      "title": "上海纽约大学2026年本科招生简章（中国大陆学生）",
      "url": "https://shanghai.nyu.edu/cn/page/shang-hai-niu-yue-da-xue2026-nian-ben-ke-zhao-sheng-jian-zhang-zhong-guo-da-lu-xue-sheng",
      "date": "2025-11-26",
      "confidence": "high"
    },
    "notes": "招生计划不分省；须网申并参加校园日活动，不存在不申请即可录取的批次"
  },
  "4132016406": {
    "schoolName": "昆山杜克大学",
    "year": 2026,
    "regularProvinces": [],
    "comprehensiveProvinces": [
      "all"
    ],
    "source": {
      "title": "昆山杜克大学2026年本科招生章程",
      "url": "https://newstatic.dukekunshan.edu.cn/admissions/2026/05/22132653/dukekunshan-undergrad-admissions-regulations-2026.pdf",
      "date": "2026-05-22",
      "confidence": "high"
    },
    "notes": "高考60%+自主综合评估40%；须经Slate系统申请并参加校园日活动入围后方可在提前批填报"
  },
  "4144014325": {
    "schoolName": "南方科技大学",
    "year": 2025,
    "regularProvinces": [],
    "comprehensiveProvinces": [
      "all"
    ],
    "source": {
      "title": "南方科技大学2025年本科招生章程",
      "url": "https://sustech.edu.cn/uploads/files/2025/11/19155008_56838.pdf",
      "date": "2025-11-19",
      "confidence": "high"
    },
    "notes": "631综合评价是唯一入学途径；全部专业在提前批（综合评价批次）录取，须参加学校能力测试"
  }
}

export const admissionChannelMeta = {
  "generatedAt": "2026-09-08T08:21:12.694Z",
  "input": "data/research/admission_channels.2026-09-08.csv",
  "schoolCount": 5
}
