// Generated by scripts/build_official_schools.mjs. Do not edit by hand.
// Source: https://www.moe.gov.cn/jyb_xxgk/s5743/s5744/202506/t20250627_1195683.html

export const officialSchoolCatalogMeta = {
  "source": "MOE National Higher Education Institution List",
  "sourcePageUrl": "https://www.moe.gov.cn/jyb_xxgk/s5743/s5744/202506/t20250627_1195683.html",
  "ordinaryAttachmentUrl": "https://www.moe.gov.cn/jyb_xxgk/s5743/s5744/202506/W020250729615142156867.xls",
  "sourceDate": "2025-06-20",
  "publishedDate": "2025-06-27",
  "ordinaryCount": 2919,
  "undergraduateCount": 1365,
  "vocationalCount": 1554,
  "adultCount": 248,
  "totalHigherEducationCount": 3167,
  "provinceCount": 31,
  "notes": "Official ordinary higher education institutions only; adult institutions are counted in metadata but excluded from the filter pool."
} as const;
