// Generated by scripts/build_official_schools.mjs. Do not edit by hand.
// Source: https://www.moe.gov.cn/jyb_xxgk/s5743/s5744/202606/t20260618_1441074.html

export const officialSchoolCatalogMeta = {
  "source": "MOE National Higher Education Institution List",
  "sourcePageUrl": "https://www.moe.gov.cn/jyb_xxgk/s5743/s5744/202606/t20260618_1441074.html",
  "ordinaryAttachmentUrl": "https://www.moe.gov.cn/jyb_xxgk/s5743/s5744/202606/W020260618416094865984.xls",
  "sourceDate": "2026-06-17",
  "publishedDate": "2026-06-18",
  "ordinaryCount": 2952,
  "undergraduateCount": 1412,
  "vocationalCount": 1540,
  "adultCount": 244,
  "totalHigherEducationCount": 3196,
  "provinceCount": 31,
  "notes": "Official ordinary higher education institutions only; adult institutions are counted in metadata but excluded from the filter pool."
} as const;
