// Generated by build_research_data.mjs.
export const researchSummary = {
  "crowdMatchedSchools": 2389,
  "crowdValuesAccepted": 44638,
  "provincePortals": 31
};
export const contributionHighlights = [
  "宿舍、空調、洗澡、假期",
  "門禁、外賣、快遞、地鐵",
  "校區位置、分校區、招生入口",
];
