// Generated by scripts/export_runtime_payloads.ts. Do not edit by hand.
export const runtimeDataManifest = {
  "version": "e4a56a351c2e",
  "schoolsPath": "/data/runtime/schools.json",
  "campusesBasePath": "/data/runtime/campuses",
  "counts": {
    "schools": 2952,
    "campusBuckets": 31,
    "campusRows": 3396
  }
} as const
