// Generated by scripts/export_runtime_payloads.ts. Do not edit by hand.
export const runtimeDataManifest = {
  "version": "10ad5e8cc1a8",
  "schoolsPath": "/data/runtime/schools.json",
  "campusesBasePath": "/data/runtime/campuses",
  "counts": {
    "schools": 2919,
    "campusBuckets": 31,
    "campusRows": 3396
  }
} as const
