// Generated by scripts/export_runtime_payloads.ts. Do not edit by hand.
export const runtimeDataManifest = {
  "version": "2026-04-21T15:21:09.842Z",
  "schoolsPath": "/data/runtime/schools.json",
  "campusesBasePath": "/data/runtime/campuses",
  "counts": {
    "schools": 2919,
    "campusBuckets": 31,
    "campusRows": 3396
  }
} as const
